# Numpy

In [1]:
import numpy as np

In [2]:
# Numpy is for array-> data of same type
# Type -> Single dimention and multi dimensional array

In [4]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr[1][1])

2
5


In [6]:
type(a)

numpy.ndarray

## Types of Array
#### Scalar = 0 Dimension , Rank=0
#### Vector = 1 Dimension , Rank=1
#### Matrix = 2 Dimension , Rank=2
#### Tensor = 3 or more Dimension , Rank=3

In [8]:
scalar=np.array(1)
scalar.ndim

0

In [9]:
vector=np.array([1,2,3])
vector.ndim

1

In [10]:
matrix=np.array([[1,2,3],[1,2,3],[1,2,3]])
matrix.ndim

2

In [11]:
tensor=np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]])
tensor.ndim

3

In [12]:
print (tensor) # as its an array you will not see comma's because its an array not list

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [13]:
# Creating array
l_array= np.array([1,2,3,4]) # from list
l_tuple= np.array((1,2,3,4)) # from tuple
print(l_array)
print(l_tuple)

[1 2 3 4]
[1 2 3 4]


#### Data type

In [18]:
int_array=np.array([1,2,3])
int_array.dtype

dtype('int32')

In [16]:
float_array=np.array([1.1,2,3])
float_array.dtype

dtype('float64')

In [17]:
string_array=np.array(["test","test1"])
string_array.dtype

dtype('<U5')

In [21]:
#forcing datatype
int_array_f=np.array([1,2,3], dtype=float)
int_array_f.dtype

dtype('float64')

In [22]:
int_array_f3=np.array([1,2,3], dtype=np.float32)
int_array_f3.dtype

dtype('float32')

In [36]:
#dtype= i1,i2,i3,i4,f2,f4,f8,u(unsign), c(complex),U(unicode),S(string),m,M(datetime)
int_array_type=np.array([1,2,3], dtype='m')
int_array_type.dtype


dtype('<m8')

In [40]:
#array of zeros
zero_arr1=np.zeros((1))
print(zero_arr1)
zero_arr2=np.zeros((2))
print(zero_arr2)
zero_arr2_2=np.zeros((2,2))
print(zero_arr2_2)
zero_arr3_3=np.zeros((3,3))
print(zero_arr3_3)

[0.]
[0. 0.]
[[0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [41]:
#array of ones
one_arr1=np.ones((1))
print(one_arr1)
one_arr2=np.ones((2))
print(one_arr2)
one_arr2_2=np.ones((2,2))
print(one_arr2_2)
one_arr3_3=np.ones((3,3))
print(one_arr3_3)

[1.]
[1. 1.]
[[1. 1.]
 [1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
#empty array - empty array is faster then zero
empty_arr1=np.empty((3))
print(empty_arr1)


[4.9e-324 9.9e-324 1.5e-323]


In [44]:
#arange: array of data with range n to m with step

arr_array=np.arange(2,8)
arr_array

array([2, 3, 4, 5, 6, 7])

In [45]:

arr_array1=np.arange(2,8,2)
arr_array1

array([2, 4, 6])

In [48]:
#linespace arrange of eqaulity divided number from n to m with x number
arr_linspace =np.linspace(2,8,num=5)
arr_linspace

array([2. , 3.5, 5. , 6.5, 8. ])

In [50]:
arr_linspace1 =np.linspace(11,20,num=10)
arr_linspace1

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [51]:
#reshape array
reshape_array=np.reshape(arr_linspace1,newshape=(2,5))
reshape_array

array([[11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]])

In [52]:
#nparray function
reshape_array.ndim


2

In [53]:
reshape_array.shape 

(2, 5)

In [54]:
reshape_array.size#number of elements

10

In [55]:
reshape_array.dtype

dtype('float64')

In [56]:
reshape_array.itemsize #dtype/8

8

In [61]:
#sort
a_unsort=np.array([5,2,3,7,9,8,0])
a_sort=np.sort(a_unsort)
print(a_sort)

[0 2 3 5 7 8 9]


In [63]:
#concatenate
a1=np.array([6,8,6,2,3,5])
a2=np.array([1,9,6,2,4,5])
a_con=np.concatenate((a1,a2))
a_con

array([6, 8, 6, 2, 3, 5, 1, 9, 6, 2, 4, 5])

In [66]:
a1_1=np.array([[6,8,6],[2,3,5]])
a2_2=np.array([[1,9,6],[2,4,5]])
a_con_1=np.concatenate((a1_1,a2_2), axis=0)
a_con_1

array([[6, 8, 6],
       [2, 3, 5],
       [1, 9, 6],
       [2, 4, 5]])

In [67]:
a_con_1=np.concatenate((a1_1,a2_2), axis=1)
a_con_1

array([[6, 8, 6, 1, 9, 6],
       [2, 3, 5, 2, 4, 5]])

#### Array Indexing and slicing

In [20]:
# Array Indexing and slicing
'''
1. If x = [4,6,17,8,9,3,15,12,7,13] convert x to ndarray and print:
a. value 17 and 7 separately using their positive index
b. value 12 and 3 using their negative index
c. the range  of values from 8 to 12 using positive indices
d. the range  of values from 4 to 15 using negative indices
e. the range  of values from 17 to the end using positive indices
f. the range  of values from 6 to the end using negative indices
g. the range  of value from 17 to 3 using a mix of negative and positive indices
h. the range  of values from 3 to 7 using a mix of negative and positive indices
i. all the values using only positive indices
j. all the values using only negative indices
k. all the values without using any index.
l. all the values from beginning to value 12
m. all the values from 6 to the end

'''
a= np.array([4,6,17,8,9,3,15,12,7,13])

print(a) 
print(a[2],a[8]) #a
print(a[-3],a[-5]) #b
print(a[3:8]) #c
print(a[-10:-3]) #d
print(a[-8:]) #e
print(a[-9:])#f
print(a[2:-4]) #g
print(a[5:-1]) #h
print(a[0:10]) #i
print(a[-10:]) #j
print(a[:]) #k
print(a[:-2]) #l
print(a[1:]) #l


[ 4  6 17  8  9  3 15 12  7 13]
17 7
12 3
[ 8  9  3 15 12]
[ 4  6 17  8  9  3 15]
[17  8  9  3 15 12  7 13]
[ 6 17  8  9  3 15 12  7 13]
[17  8  9  3]
[ 3 15 12  7]
[ 4  6 17  8  9  3 15 12  7 13]
[ 4  6 17  8  9  3 15 12  7 13]
[ 4  6 17  8  9  3 15 12  7 13]
[ 4  6 17  8  9  3 15 12]
[ 6 17  8  9  3 15 12  7 13]


In [33]:
# Array condition
'''
Create a two dimensional array for numbers between 1 and 25. Using the array, find the following:
1. all the even numbers
2. all numbers that are divisible by 4
3. all factors of 100
4. all the numbers less than or equal to 5, greater 20 or equal to 15
5. all odd numbers that are divisible by six
'''
a=np.arange(1,26)
print(a[(a%2==0)])
print(a[(a%4==0)])
print(a[(100%a==0)])
print(a[(a<=5) | (a>20) |(a==15)]) # or condition
print(a[(a%2==1) & (a%6==0)]) # and condition

[ 2  4  6  8 10 12 14 16 18 20 22 24]
[ 4  8 12 16 20 24]
[ 1  2  4  5 10 20 25]
[ 1  2  3  4  5 15 21 22 23 24 25]
[]


In [44]:
# 2D array
'''
a. Create a two dimensional array for numbers between 1 and 25.
Using the array, find the following:
1. all the numbers in the row 0
2. all the numbers in the column 2
3. numbers between 16 and 18
4. number 16, 17, 18, 21, 22 and 23
5. number 13
6. all the numbers in row 2 and 3
7. all the numbers in column 2 and 3
'''
a= np.arange(1,26).reshape(5,5)
print(a)
print(a[0])
print(a[:,2:3])
print(a[3,:3])
print(a[3:,:3])
print(a[2,2])
print(a[2:4])
print(a[:,2:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[[ 3]
 [ 8]
 [13]
 [18]
 [23]]
[16 17 18]
[[16 17 18]
 [21 22 23]]
13
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [47]:
#3D array
'''
Create a 3-D numpy array with numbers from 1 to 72.
Using the above array, print:
1. number 10
2. the first 2-D in the 3-D array
3. number 31 to 36
4. number 63 to 65
5. number 35
6. number 10, 34 and 66
7. column 3 in the third 2-D in the 3-D array
8. number 34 and 35
9. the first row in the last 2-D in the 3-D array
10. the last 2-D in the 3-D array
11. first row each in the second and third 2-D in the 3-D array
12. number 26 and 50
13. first two rows each from all the 2-D in the 3-D array
14. the entire last column of the 3-D array
15. the entire third column of the second and last 2-D in the 3-D
16. number less than 50 in the 3rd column of the second and last 2-D in the 3-D
17. numbers that are divisible by 5 in column 2 of second and third 2-D in the 3-D array
'''
a= np.arange(1,73).reshape(3,4,6)
print(a)


[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]
  [37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]
  [61 62 63 64 65 66]
  [67 68 69 70 71 72]]]


In [86]:
#print(a[0,1,3])#1
#print(a[0]) #2
#print(a[1,1])#3
#print(a[2,2,2:5])#4
#print(a[1,1,4])#5
#print(a[0][1][3], a[1][1][3],a[2][2][5])#6
#print(a[2,:,2:3])#7
#print(a[1,1,3:5])#8
#print(a[2,0])#9
#print(a[2])#10
#print(a[1:,0])#11
#print(a[1:,0,1:2])#12
#print(a[:,0:2])#13
#print(a[:,:,5:])#14
#print(a[1:,:,2:3])#15

print(a[1:,:,2:3][a[1:,:,2:3]<50])#16
print(a[1:,:,2:3][a[1:,:,2:3]%5==0])#17

[27 33 39 45]
[45]


In [90]:
#### array flattern & Ravel

b= np.arange(1,26).reshape(5,5)
b
print(b.flatten()) #shallow copy
print(b.ravel()) #deep copy
print(b.flatten().copy()) #deep copy


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [91]:
#Transpose
b= np.arange(1,26).reshape(5,5)
b.transpose()

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [94]:
#reverse
b= np.arange(1,26).reshape(5,5)
print(np.flip(b))
print(np.flip(b, axis=0)) #rows
print(np.flip(b, axis=1)) #column

[[25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


In [102]:
#unique array
d= np.concatenate((b,b), axis=1)
y= np.unique(d)
print(y)
z,ind= np.unique(d, return_index=True) #get index
print(z,ind)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25] [ 0  1  2  3  4 10 11 12 13 14 20 21 22 23 24 30 31 32 33 34 40 41 42 43
 44]


In [109]:
#min, max , sum
b= np.arange(1,26).reshape(5,5)
print(b.min())
print(b.max())
print(b.sum())

#along axis
print(b.min(axis=0))
print(b.min(axis=1))
print(b.max(axis=0))
print(b.max(axis=1))
print(b.sum(axis=0))
print(b.sum(axis=1))


1
25
325
[1 2 3 4 5]
[ 1  6 11 16 21]
[21 22 23 24 25]
[ 5 10 15 20 25]
[55 60 65 70 75]
[ 15  40  65  90 115]


In [110]:
a=np.array([[1,2,3],[6,7,8]])
b=np.array([[4,5,9],[11,12,15]])

In [112]:
# Array stacking
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[ 1  2  3  4  5  9]
 [ 6  7  8 11 12 15]]
[[ 1  2  3]
 [ 6  7  8]
 [ 4  5  9]
 [11 12 15]]


In [125]:
#Array split
x=np.arange(1,49).reshape(2,24)
print(np.hsplit(x,6))# split into 6 equal array with column
print(np.vsplit(x,2)) # split into 2 equal array with rows

a,b,c=np.hsplit(x,(5,8))# split unequal array from 0-4 then 5 -7 and rest
print(a,b,c)

[array([[ 1,  2,  3,  4],
       [25, 26, 27, 28]]), array([[ 5,  6,  7,  8],
       [29, 30, 31, 32]]), array([[ 9, 10, 11, 12],
       [33, 34, 35, 36]]), array([[13, 14, 15, 16],
       [37, 38, 39, 40]]), array([[17, 18, 19, 20],
       [41, 42, 43, 44]]), array([[21, 22, 23, 24],
       [45, 46, 47, 48]])]
[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48]])]
[[ 1  2  3  4  5]
 [25 26 27 28 29]] [[ 6  7  8]
 [30 31 32]] [[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]]


In [126]:
#copy

b=x.copy()
c=x[1:3,1:].copy()

print(b)
print(c)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]]
[[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]]


In [127]:
#array operator
a=np.array( [1,2,3,4,5])
b=np.array([6,7,8,9,10])

print(a+b)
print(a-b)
print(2*a)
print(b**2)
print (a*b)
print(a%2)
print(b/a)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 2  4  6  8 10]
[ 36  49  64  81 100]
[ 6 14 24 36 50]
[1 0 1 0 1]
[6.         3.5        2.66666667 2.25       2.        ]


In [129]:
# delete
b= np.delete(a,3)
print (b)

x=[3,4]

c=np.setdiff1d(a,x)
print(c)

[1 2 3 5]
[1 2 5]


In [138]:
# insert
print(a)
b= np.append(a,44)  #at end
print (b)
b= np.append(a,[44,45,46]) #at end
print (b)

b= np.insert(a,2,66) #after element 2
print (b)
b= np.insert(a,1,[66,67,68]) #after element 1
print (b)

[1 2 3 4 5]
[ 1  2  3  4  5 44]
[ 1  2  3  4  5 44 45 46]
[ 1  2 66  3  4  5]
[ 1 66 67 68  2  3  4  5]


In [144]:
# New axis

a= np.arange(1,6)
a
b= a[np.newaxis,:] # add new dimention as row
c= a[:,np.newaxis] # add new dimention as column
d= a[np.newaxis,:,np.newaxis]
print(b)
print(b.ndim)
print(b.shape)
print(c)
print(c.ndim)
print(c.shape)
print(d)
print(d.ndim)
print(d.shape)

[[1 2 3 4 5]]
2
(1, 5)
[[1]
 [2]
 [3]
 [4]
 [5]]
2
(5, 1)
[[[1]
  [2]
  [3]
  [4]
  [5]]]
3
(1, 5, 1)


In [145]:
#Trigonomatry
#1 degree= pi/180 radian
import numpy as np
np.sin(90)
np.sin(90*np.pi/180)
np.cos(60)
np.cos(60*np.pi/180)
np.tan(70)
np.tan(60*np.pi/180)

1.7320508075688767

In [151]:
# searching in array
a= np.arange(1,11)
print (a)

print( np.where(a==6)) #index 5
print( np.where(a%2==0)) # index of 2,4,6,8,10

[ 1  2  3  4  5  6  7  8  9 10]
(array([5], dtype=int64),)
(array([1, 3, 5, 7, 9], dtype=int64),)


In [154]:
# Multiplication

a= np.arange(1,5).reshape(2,2)
b= np.arange(6,10).reshape(2,2)
print(np.multiply(a,5))
print(np.dot(a,b)) # matrix multiplication


[[ 5 10]
 [15 20]]
[[22 25]
 [50 57]]


In [156]:
# trace => sum of diagonal

a= np.arange(1,13).reshape(4,3)
print(a)
print(np.trace(a))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
15


In [157]:
#outer Product => each number by each number =>4*4=16
a= np.arange(1,5).reshape(2,2)
b= np.arange(6,10).reshape(2,2)
print(a)
print(b)
print(np.outer(a,b))


[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[ 6  7  8  9]
 [12 14 16 18]
 [18 21 24 27]
 [24 28 32 36]]


In [158]:
#inner product => each row by row =>Xrow1 *Yrow1, Xrow1 *Yrow2, Xrow2* Yrow1=> 4*4=>4
a= np.arange(1,5).reshape(2,2)
b= np.arange(6,10).reshape(2,2)
print(a)
print(b)
print(np.inner(a,b))

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[20 26]
 [46 60]]


In [159]:
#cross product Xrow1 *Yrow 1 , Xrow2* Yrow2 4*4=>2
a= np.arange(1,5).reshape(2,2)
b= np.arange(6,10).reshape(2,2)
print(a)
print(b)
print(np.cross(a,b))

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[-5 -5]


In [160]:
#kronecker product multiply each number of x with y 4*4 =16
#x1*y=4, x2*y=4 and so one 4+4+4+4
a= np.arange(1,5).reshape(2,2)
b= np.arange(6,10).reshape(2,2)
print(a)
print(b)
print(np.kron(a,b))

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[ 6  7 12 14]
 [ 8  9 16 18]
 [18 21 24 28]
 [24 27 32 36]]


In [161]:
#determinant same as matrix
a= np.arange(1,10).reshape(3,3)

print(a)

print(np.linalg.det(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16


In [163]:
#inverse same as matrix (transpose(cofactor)/determinant)
a= np.arange(1,10).reshape(3,3)
print(a)
print(np.linalg.inv(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [164]:
#Condition Number
#its a number if added to a function it effect the function
x= np.array([[2,3],[6,7]])
print(np.linalg.cond(x))

24.459115447074858


## Random

In [166]:
from numpy import random

In [176]:
#random integer
print (random.randint(20))# number between 1-20
print (random.rand(5))# 5 number between 0 to 1

print (random.randint(20,size=(5)))# number between 1-20 get 5 number
print (random.randint(20,size=(4,2)))# number between 1-20 get 4*2 array

#choice
a= np.array([4,5,9,20,1,2,11,15])
print (random.choice(a))# get number from a
print (random.choice(a,size=(5)))# get 5 number from a
print (random.choice(a,size=(4,2)))# get 4 by 2 number from a



5
[0.04251424 0.18701012 0.70244994 0.69992192 0.45363417]
[17  0  2 14 17]
[[ 9  1]
 [12  3]
 [ 7  9]
 [11 11]]
15
[ 9  1 20  4  1]
[[ 4  9]
 [ 5 11]
 [ 5  9]
 [ 2  4]]


In [183]:
# seed => it will choose same random number , result will be same every time
random.seed(0)
print (random.randint(20, size=(5)))# number between 1-20 ##[12 15  0  3  3]
random.seed(1)
print (random.randint(20, size=(5)))# number between 1-20 ##[ 5 11 12  8  9]
random.seed(2)
a= np.array([4,5,9,20,1,2,11,15])
print (random.choice(a,size=(5)))# [ 4 15  2  4 11]

[12 15  0  3  3]
[ 5 11 12  8  9]
[ 4 15  2  4 11]


In [187]:
# data distribution 
print (random.choice([3,4,6],p=[.2,.5,.3],size=(20))) # p is probability of 3,4,6 respectively
print (random.choice([3,4,6],p=[.2,.5,.3],size=(4,5)))

[4 6 6 6 4 4 4 4 6 4 6 6 4 6 4 6 4 6 4 4]
[[4 4 3 4 4]
 [6 6 4 6 6]
 [6 6 3 6 6]
 [6 4 4 4 4]]


# Panda

In [188]:
#pip install pandas

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



In [1]:
import pandas as pd

  students  Scores
0     John      80
1     Paul      40
2    James      60
3     Rita      90


In [4]:
#series
y= [2,3,4,5]
x=pd.Series(y)
print(x)

0    2
1    3
2    4
3    5
dtype: int64


In [8]:
# label
y= [2,3,4,5]
x=pd.Series(y, index=['a','b','c','d'])
print(x['c'])

4


In [11]:
# label
y= {'a':2,'b':3,'c':4,'d':5}
x=pd.Series(y)
print(x['c'])
z=pd.Series(y,index=['a','b'])
print(z)

4
a    2
b    3
dtype: int64


In [12]:
#dataframe

data={
    'students':['John','Paul','James','Rita'],
    'Scores':[80,40,60,90]
}
x=pd.DataFrame(data)
print(x)

  students  Scores
0     John      80
1     Paul      40
2    James      60
3     Rita      90


In [14]:
print(x.loc[1])
print(x.loc[[2,3]])

students    Paul
Scores        40
Name: 1, dtype: object
  students  Scores
2    James      60
3     Rita      90


In [15]:
import pandas as pd

a = [3,4,6,7,9]
b = [1,3,6,3,4]
a_series = pd.Series(a)
b_series = pd.Series(b)
pd.concat([a_series,b_series])

0    3
1    4
2    6
3    7
4    9
0    1
1    3
2    6
3    3
4    4
dtype: int64

In [16]:
import pandas as pd

a = [3,4,6,7,9]
b = [1,3,6,3,4]
a_series = pd.Series(a)
b_series = pd.Series(b)
pd.concat([a_series,b_series], keys = ['First', 'Second'])

First   0    3
        1    4
        2    6
        3    7
        4    9
Second  0    1
        1    3
        2    6
        3    3
        4    4
dtype: int64

In [17]:
import pandas as pd

a = [3,4,6,7,9]
b = [1,3,6,3,4]
a_series = pd.Series(a)
b_series = pd.Series(b)
pd.concat([a_series,b_series], keys = ['First', 'Second'], names=['group, index'])
# keys for each dataframe and index can be any word but it define index of column

group, index   
First         0    3
              1    4
              2    6
              3    7
              4    9
Second        0    1
              1    3
              2    6
              3    3
              4    4
dtype: int64

In [18]:
import pandas as pd

a = [[3,4,6],[1,2,3]]
b = [[1,3,6],[4,7,8]]
a_df = pd.DataFrame(a)
b_df = pd.DataFrame(b)
df = pd.concat([a_df, b_df])
df

0  1  2
0  3  4  6
1  1  2  3
0  1  3  6
1  4  7  8

In [19]:
import pandas as pd

a = [3,4,6,9]
b = [['pen',2,4], ['rer',8,9]]
a_df = pd.DataFrame(a)
b_df = pd.DataFrame(b, columns=['letters', 'numbers', 'numbers2'])
pd.concat([a_df,b_df])

0 letters  numbers  numbers2
0  3.0     NaN      NaN       NaN
1  4.0     NaN      NaN       NaN
2  6.0     NaN      NaN       NaN
3  9.0     NaN      NaN       NaN
0  NaN     pen      2.0       4.0
1  NaN     rer      8.0       9.0

In [21]:
import pandas as pd

a = [[3,4,6], [1,2,3]]
b = [[1,3,6],[4,7,8]]
a_df = pd.DataFrame(a, columns=['n', 'o', 'p'])
b_df = pd.DataFrame(b, columns=['n', 'o', 'p'])
pd.concat([a_df, b_df], axis =1) 
pd.concat([a_df, b_df], axis =0)

n  o  p
0  3  4  6
1  1  2  3
0  1  3  6
1  4  7  8

In [22]:
import pandas as pd
df_1 = pd.DataFrame({
    'Name':['Peter','Ahmed','James','Kate'],
    'Salary':[22000,35000,77000,25000]
})

df_2 = pd.DataFrame({
    'Name':['Peter','Ahmed','James','Kate'],
    'Department':['Sales','Admin','IT','HR']
})
df_3 = pd.merge(df_1, df_2, on='Name')
df_3

Name  Salary Department
0  Peter   22000      Sales
1  Ahmed   35000      Admin
2  James   77000         IT
3   Kate   25000         HR

In [27]:
import pandas as pd

df_1 = pd.DataFrame({
    'Name':['Peter','Ahmed','James','Kate'],
    'Salary':[22000,35000,77000,25000]
})
df_2 = pd.DataFrame({
    'Name':['Peter','Ahmed','Kate'],
    'Department':['Sales','Admin','HR']
})
df_3 = pd.merge(df_1, df_2, on='Name') # inner join
df_3
df_6 = pd.merge(df_1,df_2,on='Name', how='inner') # same as above # intersect
df_6
df_7 = pd.merge(df_1,df_2,on='Name', how='outer') #union
df_7
df_8 = pd.merge(df_1,df_2,on='Name', how='left') #all from left
df_8
df_9 = pd.merge(df_1,df_2,on='Name', how='right') #all from right
df_9

Name  Salary Department
0  Peter   22000      Sales
1  Ahmed   35000      Admin
2   Kate   25000         HR

In [30]:
import pandas as pd

df_1 = pd.DataFrame({
    'Name':['Peter','Ahmed','James','Kate'],
    'Salary':[22000,35000,77000,25000],
    'Department':['Sales','Admin','IT','HR'],
    'Education':['Bsc','Bsc','MSc','MA']
})
df_2 = pd.DataFrame({
    'Name':['Peter','Ahmed','James','Kate'],
    'Department':['Sales','Admin','IT','HR'],
    'Education':['Bsc','Bsc','MSc','MA']
})

df_3 = pd.merge(df_1,df_2,on='Name')
df_3 = pd.merge(df_1,df_2,on='Name', suffixes=('_first', '_second'))
df_3

Name  Salary Department_first Education_first Department_second  \
0  Peter   22000            Sales             Bsc             Sales   
1  Ahmed   35000            Admin             Bsc             Admin   
2  James   77000               IT             MSc                IT   
3   Kate   25000               HR              MA                HR   

  Education_second  
0              Bsc  
1              Bsc  
2              MSc  
3               MA

In [56]:
df=pd.read_csv('DataForDatascience/world-happiness-report.csv')
#print(df.to_string())
print(df.head())
#print(df.tail())
#print(df.info()) # information about dataframe
#print(df.describe()) # statistics
#print(df.describe(percentiles=[.2,.6,.8])) # statistics

  Country name  year  Life Ladder  Log GDP per capita  Social support  \
0  Afghanistan  2008        3.724               7.370           0.451   
1  Afghanistan  2009        4.402               7.540           0.552   
2  Afghanistan  2010        4.758               7.647           0.539   
3  Afghanistan  2011        3.832               7.620           0.521   
4  Afghanistan  2012        3.783               7.705           0.521   

   Healthy life expectancy at birth  Freedom to make life choices  Generosity  \
0                             50.80                         0.718       0.168   
1                             51.20                         0.679       0.190   
2                             51.60                         0.600       0.121   
3                             51.92                         0.496       0.162   
4                             52.24                         0.531       0.236   

   Perceptions of corruption  Positive affect  Negative affect  
0        

In [51]:
df['Freedom to make life choices'].min() # min max of specific colum
df['Freedom to make life choices'].max()

country=['Singapore']

d_filter=df[df['Country name'].isin(country)] # get only singapore data
d_filter

d_filter['Freedom to make life choices'].min() # min max of specific colum
d_filter['Freedom to make life choices'].max()

df['Perceptions of corruption'].mean()
df['Perceptions of corruption'].median()
df['Perceptions of corruption'].mode()

df['Generosity'].sum()
df['Generosity'].sum(skipna=True) # same as above

df.mean(axis=1)
df.mean(axis=0)

C:\Users\ankur\AppData\Local\Temp\ipykernel_13772\2690680807.py:19: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean(axis=1)
C:\Users\ankur\AppData\Local\Temp\ipykernel_13772\2690680807.py:20: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean(axis=0)


year                                2013.216008
Life Ladder                            5.466705
Log GDP per capita                     9.368453
Social support                         0.812552
Healthy life expectancy at birth      63.359374
Freedom to make life choices           0.742558
Generosity                             0.000103
Perceptions of corruption              0.747125
Positive affect                        0.710003
Negative affect                        0.268544
dtype: float64

In [53]:
df.count()

Country name                        1949
year                                1949
Life Ladder                         1949
Log GDP per capita                  1913
Social support                      1936
Healthy life expectancy at birth    1894
Freedom to make life choices        1917
Generosity                          1860
Perceptions of corruption           1839
Positive affect                     1927
Negative affect                     1933
dtype: int64

In [54]:
df.count(axis=1)

0       11
1       11
2       11
3       11
4       11
        ..
1944    11
1945    11
1946    11
1947    11
1948    11
Length: 1949, dtype: int64

In [55]:
# Json file

#pd.read_json()



In [57]:
file2 = pd.read_csv('world-happiness-report.csv', header=1)#Skip Rows Reading CSV File 


file2 = pd.read_csv('world-happiness-report.csv', skiprows=[2,3,4,6])
file2 = pd.read_csv('world-happiness-report.csv', skiprows=[0])
file2 = pd.read_csv('world-happiness-report.csv', skiprows=4)
file2 = pd.read_csv('world-happiness-report.csv', header = None)

file2 = pd.read_csv('world-happiness-report.csv', header = None, prefix='header_')


file = pd.read_csv('world-happiness-report.csv', usecols=['year', 'Generosity'])

file = pd.read_csv('world-happiness-report.csv', usecols=[3, 6, 0, 2])

file = pd.read_csv('world-happiness-report.csv', nrows=19)
file = pd.read_csv('world-happiness-report.csv', usecols=[0,1,3],nrows=6)


file = pd.read_csv('world-happiness-report.csv', verbose=True)

file = pd.read_csv('world-happiness-report.csv', dtype={'year':'float64'})

file.dtypes


file = pd.read_csv('world-happiness-report.csv')

file.info()

country = file['Country name']

country.head()

country.tail()



x = file[['Country name', 'year', 'Generosity']]

x.head()

x.tail()


data = pd.read_csv('world-happiness-report.csv')



data

data.shape

data.shape[0]

data.shape[1]

import pandas as pd

data = pd.read_csv('world-happiness-report.csv')

data.tail(n=10)

FileNotFoundError: [Errno 2] No such file or directory: 'world-happiness-report.csv'

In [ ]:
loc vs iloc

Head vs iloc vs loc
data.head(n=11)

data.loc[:10]

data.iloc[:11]

tail vs
data.tail(n=1)

data.loc[1948:1948]
data.iloc[1948]
data.iloc[-1:]



columns

data.iloc[:,[0,1,7]]

data.loc[:,['Country name', 'year', 'Generosity']]

Without Using Tail or iLoc Get Last Row - Code
data.loc[data.shape[0]-1]


data.iloc[:, range(2,7)]

 Another Selection Trick - Code
column_N  =  data.shape[1]

Index_last  =  column_N - 1

data.iloc[:,Index_last:]


x=list(range(0,11,2))



data.iloc[:,x]

Even Columns Without Using Range - Code
data.iloc[:, ::2]

Pandas - Specific Row - Code
data.iloc[1944]['Social support']

data.loc[1944,'Social support']

data.iloc[1944,4]

Pandas - Column - Code
data['year']

Filtering Greater Than - Code
data[data['year']>2018]

Pandas - Filtering Greater Than with Fewer Rows - Code
data[data['year']>2018][:9]


 nlargest - Code
data.nlargest(10, 'Generosity')
Pandas - nsmallest - Code
data.nsmallest(10,'Social support')

Pandas - Sort_Values Ascending - Code
file.sort_values(by='year', ascending=True)

Sort_Values for Smallest - Code
file.sort_values(by='Generosity', ascending=True)[:5]

 Selecting a range of values - Code
data.query('0.025< Generosity <0.028')


Return Random Rows - Code
data.sample(n=8)

data.sample(frac=0.02)

Pandas - Reset Index - Code
x = data.query('0.025<Generosity<0.028')

new_data = x.reset_index()

new_data

 - Greater than 0.1 - Code
data[data.Generosity>0.1]